[package]
name = "rpgtool-common"
version = "0.1.0"
edition = "2024"

[dependencies]
alox-48.workspace = true
clap.workspace = true

serde.workspace = true
serde_json.workspace = true
ron.workspace = true
serde_yaml_ng.workspace = true

thiserror.workspace = true
