[package]
name = "marshal2conv"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
alox-48.workspace = true
serde.workspace = true
serde_json.workspace = true
common.workspace = true
